name: CD

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: git config --global user.email "abhinandhajay@gmail.com"
      - run: git config --global user.name "Abhinandh Ajay"
      - run: CI='' npm run deploy
