name: CD

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: fregante/setup-git-user@v1
        with:
          node-version: 16
      - run: npm ci
      - run: CI='' npm run deploy
