name: CD

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'Abhinandh Ajay'
          email: 'abhinandhajay@gmail.com'
          actor: 'abhinandhajay'
      - run: npm ci
      - run: CI='' npm run deploy
